In [10]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('healthcare.csv')

# Display the first few rows of the dataset to understand its structure
print(df.head())

      id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes
1  51676  Female  61.0             0              0          Yes
2  31112    Male  80.0             0              1          Yes
3  60182  Female  49.0             0              0          Yes
4   1665  Female  79.0             1              0          Yes

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked
1  Self-employed          Rural             202.21   NaN     never smoked
2        Private          Rural             105.92  32.5     never smoked
3        Private          Urban             171.23  34.4           smokes
4  Self-employed          Rural             174.12  24.0     never smoked

   stroke
0       1
1       1
2       1
3       1
4       1

In [11]:
# Assuming 'HeartDisease' column indicates presence (1) or absence (0) of heart disease
heart_disease_rows = df[df['heart_disease'] == 1]
print(heart_disease_rows)

         id  gender   age  hypertension  heart_disease ever_married work_type  \
0      9046    Male  67.0             0              1          Yes   Private
2     31112    Male  80.0             0              1          Yes   Private
6     53882    Male  74.0             1              1          Yes   Private
11    12095  Female  61.0             0              1          Yes  Govt_job
13     8213    Male  78.0             0              1          Yes   Private
...     ...     ...   ...           ...            ...          ...       ...
4855  42563  Female  57.0             1              1          Yes   Private
4869  72715  Female  50.0             0              1          Yes   Private
4921   4062    Male  72.0             0              1          Yes   Private
4986  53697    Male  58.0             0              1          Yes   Private
5008  48109  Female  79.0             0              1          Yes   Private

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke
0             Urban             228.69  36.6  formerly smoked       1
2             Rural             105.92  32.5     never smoked       1
6             Rural              70.09  27.4     never smoked       1
11            Rural             120.46  36.8           smokes       1
13            Urban             219.84   NaN          Unknown       1
...             ...                ...   ...              ...     ...
4855          Rural             231.72  45.7  formerly smoked       0
4869          Urban             193.80  26.4     never smoked       0
4921          Rural             238.27   NaN           smokes       0
4986          Rural             225.35  26.5           smokes       0
5008          Rural              88.51  24.5     never smoked       0

[276 rows x 12 columns]

In [12]:
# Assuming 'Hypertension' column indicates presence (1) or absence (0) of hypertension
hypertension_no_heart_disease_rows = df[(df['hypertension'] == 1) & (df['heart_disease'] == 0)]
print(hypertension_no_heart_disease_rows)

         id  gender   age  hypertension  heart_disease ever_married  \
4      1665  Female  79.0             1              0          Yes
10    12109  Female  81.0             1              0          Yes
15    58202  Female  50.0             1              0          Yes
17    34120    Male  75.0             1              0          Yes
21    13861  Female  52.0             1              0          Yes
...     ...     ...   ...           ...            ...          ...
5088  22190  Female  64.0             1              0          Yes
5091   6369    Male  59.0             1              0          Yes
5093  32235  Female  45.0             1              0          Yes
5100  68398    Male  82.0             1              0          Yes
5105  18234  Female  80.0             1              0          Yes

          work_type Residence_type  avg_glucose_level   bmi smoking_status  \
4     Self-employed          Rural             174.12  24.0   never smoked
10          Private          Rural              80.43  29.7   never smoked
15    Self-employed          Rural             167.41  30.9   never smoked
17          Private          Urban             221.29  25.8         smokes
21    Self-employed          Urban             233.29  48.9   never smoked
...             ...            ...                ...   ...            ...
5088  Self-employed          Urban              76.89  30.2        Unknown
5091        Private          Rural              95.05  30.9   never smoked
5093       Govt_job          Rural              95.02   NaN         smokes
5100  Self-employed          Rural              71.97  28.3   never smoked
5105        Private          Urban              83.75   NaN   never smoked

      stroke
4          1
10         1
15         1
17         1
21         1
...      ...
5088       0
5091       0
5093       0
5100       0
5105       0

[434 rows x 12 columns]

In [13]:
# Check for missing values in the dataset
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

# Option 1: Drop rows with missing values
cleaned_df_drop = df.dropna()
print("Data after dropping rows with missing values:\n", cleaned_df_drop)

# Option 2: Fill missing values with mean or other appropriate values
# For numerical columns, you can fill missing values with the column mean
for column in df.select_dtypes(include=np.number).columns:
    df[column].fillna(df[column].mean(), inplace=True)

# For categorical columns, you can fill missing values with the mode (most frequent value)
for column in df.select_dtypes(include='object').columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

print("Data after filling missing values:\n", df)

Missing values in each column:
 id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64
Data after dropping rows with missing values:
          id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes
2     31112    Male  80.0             0              1          Yes
3     60182  Female  49.0             0              0          Yes
4      1665  Female  79.0             1              0          Yes
5     56669    Male  81.0             0              0          Yes
...     ...     ...   ...           ...            ...          ...
5104  14180  Female  13.0             0              0           No
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked
2           Private          Rural             105.92  32.5     never smoked
3           Private          Urban             171.23  34.4           smokes
4     Self-employed          Rural             174.12  24.0     never smoked
5           Private          Urban             186.21  29.0  formerly smoked
...             ...            ...                ...   ...              ...
5104       children          Rural             103.08  18.6          Unknown
5106  Self-employed          Urban             125.20  40.0     never smoked
5107  Self-employed          Rural              82.99  30.6     never smoked
5108        Private          Rural             166.29  25.6  formerly smoked
5109       Govt_job          Urban              85.28  26.2          Unknown

      stroke
0          1
2          1
3          1
4          1
5          1
...      ...
5104       0
5106       0
5107       0
5108       0
5109       0

[4909 rows x 12 columns]
Data after filling missing values:
          id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes
1     51676  Female  61.0             0              0          Yes
2     31112    Male  80.0             0              1          Yes
3     60182  Female  49.0             0              0          Yes
4      1665  Female  79.0             1              0          Yes
...     ...     ...   ...           ...            ...          ...
5105  18234  Female  80.0             1              0          Yes
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type Residence_type  avg_glucose_level        bmi  \
0           Private          Urban             228.69  36.600000
1     Self-employed          Rural             202.21  28.893237
2           Private          Rural             105.92  32.500000
3           Private          Urban             171.23  34.400000
4     Self-employed          Rural             174.12  24.000000
...             ...            ...                ...        ...
5105        Private          Urban              83.75  28.893237
5106  Self-employed          Urban             125.20  40.000000
5107  Self-employed          Rural              82.99  30.600000
5108        Private          Rural             166.29  25.600000
5109       Govt_job          Urban              85.28  26.200000

       smoking_status  stroke
0     formerly smoked       1
1        never smoked       1
2        never smoked       1
3              smokes       1
4        never smoked       1
...               ...     ...
5105     never smoked       0
5106     never smoked       0
5107     never smoked       0
5108  formerly smoked       0
5109          Unknown       0

[5110 rows x 12 columns]

In [14]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('healthcare.csv')

# Display the first few rows of the dataset to understand its structure
print("First few rows of the dataset:\n", df.head())

# Display rows that have heart disease
heart_disease_rows = df[df['heart_disease'] == 1]
print("Rows with heart disease:\n", heart_disease_rows)

# Display rows that have hypertension and no heart disease
hypertension_no_heart_disease_rows = df[(df['hypertension'] == 1) & (df['heart_disease'] == 0)]
print("Rows with hypertension and no heart disease:\n", hypertension_no_heart_disease_rows)

# Check for missing values in the dataset
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

# Option 1: Drop rows with missing values
cleaned_df_drop = df.dropna()
print("Data after dropping rows with missing values:\n", cleaned_df_drop)

# Option 2: Fill missing values with mean or other appropriate values
# For numerical columns, you can fill missing values with the column mean
for column in df.select_dtypes(include=np.number).columns:
    df[column].fillna(df[column].mean(), inplace=True)

# For categorical columns, you can fill missing values with the mode (most frequent value)
for column in df.select_dtypes(include='object').columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

print("Data after filling missing values:\n", df)

First few rows of the dataset:
       id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes
1  51676  Female  61.0             0              0          Yes
2  31112    Male  80.0             0              1          Yes
3  60182  Female  49.0             0              0          Yes
4   1665  Female  79.0             1              0          Yes

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked
1  Self-employed          Rural             202.21   NaN     never smoked
2        Private          Rural             105.92  32.5     never smoked
3        Private          Urban             171.23  34.4           smokes
4  Self-employed          Rural             174.12  24.0     never smoked

   stroke
0       1
1       1
2       1
3       1
4       1
Rows with heart disease:
          id  gender   age  hypertension  heart_disease ever_married work_type  \
0      9046    Male  67.0             0              1          Yes   Private
2     31112    Male  80.0             0              1          Yes   Private
6     53882    Male  74.0             1              1          Yes   Private
11    12095  Female  61.0             0              1          Yes  Govt_job
13     8213    Male  78.0             0              1          Yes   Private
...     ...     ...   ...           ...            ...          ...       ...
4855  42563  Female  57.0             1              1          Yes   Private
4869  72715  Female  50.0             0              1          Yes   Private
4921   4062    Male  72.0             0              1          Yes   Private
4986  53697    Male  58.0             0              1          Yes   Private
5008  48109  Female  79.0             0              1          Yes   Private

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke
0             Urban             228.69  36.6  formerly smoked       1
2             Rural             105.92  32.5     never smoked       1
6             Rural              70.09  27.4     never smoked       1
11            Rural             120.46  36.8           smokes       1
13            Urban             219.84   NaN          Unknown       1
...             ...                ...   ...              ...     ...
4855          Rural             231.72  45.7  formerly smoked       0
4869          Urban             193.80  26.4     never smoked       0
4921          Rural             238.27   NaN           smokes       0
4986          Rural             225.35  26.5           smokes       0
5008          Rural              88.51  24.5     never smoked       0

[276 rows x 12 columns]
Rows with hypertension and no heart disease:
          id  gender   age  hypertension  heart_disease ever_married  \
4      1665  Female  79.0             1              0          Yes
10    12109  Female  81.0             1              0          Yes
15    58202  Female  50.0             1              0          Yes
17    34120    Male  75.0             1              0          Yes
21    13861  Female  52.0             1              0          Yes
...     ...     ...   ...           ...            ...          ...
5088  22190  Female  64.0             1              0          Yes
5091   6369    Male  59.0             1              0          Yes
5093  32235  Female  45.0             1              0          Yes
5100  68398    Male  82.0             1              0          Yes
5105  18234  Female  80.0             1              0          Yes

          work_type Residence_type  avg_glucose_level   bmi smoking_status  \
4     Self-employed          Rural             174.12  24.0   never smoked
10          Private          Rural              80.43  29.7   never smoked
15    Self-employed          Rural             167.41  30.9   never smoked
17          Private          Urban             221.29  25.8         smokes
21    Self-employed          Urban             233.29  48.9   never smoked
...             ...            ...                ...   ...            ...
5088  Self-employed          Urban              76.89  30.2        Unknown
5091        Private          Rural              95.05  30.9   never smoked
5093       Govt_job          Rural              95.02   NaN         smokes
5100  Self-employed          Rural              71.97  28.3   never smoked
5105        Private          Urban              83.75   NaN   never smoked

      stroke
4          1
10         1
15         1
17         1
21         1
...      ...
5088       0
5091       0
5093       0
5100       0
5105       0

[434 rows x 12 columns]
Missing values in each column:
 id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64
Data after dropping rows with missing values:
          id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes
2     31112    Male  80.0             0              1          Yes
3     60182  Female  49.0             0              0          Yes
4      1665  Female  79.0             1              0          Yes
5     56669    Male  81.0             0              0          Yes
...     ...     ...   ...           ...            ...          ...
5104  14180  Female  13.0             0              0           No
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked
2           Private          Rural             105.92  32.5     never smoked
3           Private          Urban             171.23  34.4           smokes
4     Self-employed          Rural             174.12  24.0     never smoked
5           Private          Urban             186.21  29.0  formerly smoked
...             ...            ...                ...   ...              ...
5104       children          Rural             103.08  18.6          Unknown
5106  Self-employed          Urban             125.20  40.0     never smoked
5107  Self-employed          Rural              82.99  30.6     never smoked
5108        Private          Rural             166.29  25.6  formerly smoked
5109       Govt_job          Urban              85.28  26.2          Unknown

      stroke
0          1
2          1
3          1
4          1
5          1
...      ...
5104       0
5106       0
5107       0
5108       0
5109       0

[4909 rows x 12 columns]
Data after filling missing values:
          id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes
1     51676  Female  61.0             0              0          Yes
2     31112    Male  80.0             0              1          Yes
3     60182  Female  49.0             0              0          Yes
4      1665  Female  79.0             1              0          Yes
...     ...     ...   ...           ...            ...          ...
5105  18234  Female  80.0             1              0          Yes
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type Residence_type  avg_glucose_level        bmi  \
0           Private          Urban             228.69  36.600000
1     Self-employed          Rural             202.21  28.893237
2           Private          Rural             105.92  32.500000
3           Private          Urban             171.23  34.400000
4     Self-employed          Rural             174.12  24.000000
...             ...            ...                ...        ...
5105        Private          Urban              83.75  28.893237
5106  Self-employed          Urban             125.20  40.000000
5107  Self-employed          Rural              82.99  30.600000
5108        Private          Rural             166.29  25.600000
5109       Govt_job          Urban              85.28  26.200000

       smoking_status  stroke
0     formerly smoked       1
1        never smoked       1
2        never smoked       1
3              smokes       1
4        never smoked       1
...               ...     ...
5105     never smoked       0
5106     never smoked       0
5107     never smoked       0
5108  formerly smoked       0
5109          Unknown       0

[5110 rows x 12 columns]